apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
  # "gcr.io/project-id/nats-operator" is used to make it easy to support both local (Minikube, ...) and GKE deployments.
  # To deploy to GKE, "project-id" must be replaced by the correct project ID, and the Cloud Build API must be enabled for said project.
  - image: gcr.io/project-id/nats-operator
    docker:
      # Use a Dockerfile specific for development only.
      dockerfile: hack/skaffold/operator/Dockerfile
deploy:
  kubectl:
    manifests:
    # We must make sure that the required service account, cluster role and cluster role binding are in place.
    # Hence, we deploy "deploy/default-rbac.yaml" as well.
    - deploy/default-rbac.yaml
    # We deploy a single "nats-operator" pod to make debugging easier.
    # NOTE: Any changes made to the podspec in "deploy/deployment.yaml" will have to be replayed on this file.
    - hack/skaffold/operator/pod.yml
profiles:
- name: gke
  build:
    # For the "gke" profile, we must use the Google Cloud Build API to build the image.
    googleCloudBuild: {}
- name: local
  build:
    # For the "local" profile, we must perform the build locally.
    local: {}
